### ISSUE TITLE
add and parse data from lynis

### ISSUE THREAD

**Issue by ukastens** [idb-project/the-idb#287]
lynis allows compliance report that should be uploaded to a remote host. Since this report could give some information about comliance information it would be great to add that data - maybe as addon to puppet data or as an new reporting

example data: 
# Lynis Report
report_version_major=1
report_version_minor=0
report_datetime_start=2017-03-09 06:10:52
auditor=[Not Specified]
lynis_version=2.4.3
os=macOS
os_name=Mac OS X
os_fullname=Mac OS X 10.10 (Yosemite)
os_version=10.10.5
os_kernel_version=14.5.0
hostname=ennits-MBP
test_category=all
test_group=all

**Comment by dra** [comment]
We just created #346 in order to keep track of data sent to the API, depending from which source (aka API token) they were delivered. So it is possbile to have latest data from lynis along with latest data from puppetDB along with latest data from Bacula ...

**Comment by dra** [comment]
Just finished this task and the code got merged. Now it is possible to pass Lynis data via the API with only small adaptions to the attribute names:

`curl -k -g -X PUT -H "Content-Type: application/json" -d '{"create_machine": true, "report_version_major": "1", "report_version_minor": "0", "report_datetime_start": "2017-03-09 06:10:52", "auditor": "[Not Specified]", "lynis_version": "2.4.3", "os": "macOS", "os_name": "Mac OS X", "os_fullname": "Mac OS X 10.10 (Yosemite)", "os_release": "10.10.5", "os_kernel_version": "14.5.0", "test_category": "all", "test_group": "all", "fqdn": "ennits-MBP.example.com", "aliases": [{"name":"ennits-MBP"}] }' http://localhost:3000/api/v2/machines?idb_api_token=eijuulooB1ae`

This enters the hostname as alias, OS and OS release to the machine facts, and stores all attributes as API data in a "Lynis" section:

![lynis](https://cloud.githubusercontent.com/assets/130295/24021054/3b70a3aa-0a9f-11e7-8318-73b1e4ee052e.png)

The API data sections are separated by the API tokens used, aka the sources the data originates from.
