### ISSUE TITLE
RFF: Ability to select fields returned by APi query

### ISSUE THREAD

**Issue by ecm75** [idb-project/the-idb#373]
It would be very nice if one could (optionally) select which datafields are returned for a machine when querying via API, since especially the software and puppet-raw-data fields return a huge amount of data.
My idea would be to pass something like `&show=fqdn,id,arch,cores,os,os_release` to return only these fields in the JSON response.

**Comment by fkr** [comment]
This is indeed a very useful suggestion!

**Comment by rbns** [comment]
in api v3, handling the large fields could be done using a subroute like for aliases, nics, etc.
e.g. requesting /machines/{fqdn}/software instead of embedding it directly in the returned json data.

**Comment by rbns** [comment]
field selection can be implemented using conditionals in grape-entity:
https://github.com/ruby-grape/grape-entity#using-the-exposure-dsl
as filtering could be a nice optional feature i'll look into how to use this.

**Comment by rbns** [comment]
i've done a bit of prototyping for this today, currently only with the soon-too-be merged api v3 and only for one api call, getting the list of machines. while field selection works there, i still need a good idea about how to implement it so that it is usable everywhere.
