### ISSUE TITLE
RFF: Ability to filter software using < and <= comparisons

### ISSUE THREAD

**Issue by ecm75** [idb-project/the-idb#382]
Since we want to use the software search to identify machines with vulnerable software versions, we would need the ability to search for software versions using the `<` and `<=` comparisons.
Right now only the `=` comparisons seems to be available in Web and API, but with this it's not possible to find outdated software packages eg. in ubuntu since the vulnerable version is most likely a substring of the fixed version...

Example: apache2
Vulnerable software version:
  2.4.7-1ubuntu4
Fixed version:
  2.4.7-1ubuntu4.14

Searching in IDB with `=2.4.7-1ubuntu4`  lists machines with `2.4.7-1ubuntu4.14` as well.
A search with `<2.4.7-1ubuntu4.14` should not list machines with `2.4.7-1ubuntu4.14`.

**Comment by rbns** [comment]
i agree that better filtering options are desirable.

less and less equal require a defined order for package versions which is problematic to implement for multiple distributions (and operating systems). each distribution/OS has slightly different conventions when it comes to version numbers and this still doesn't cover software with unusual versioning schemes.

if < and <= are to be implemented it has to work correctly all the time as missing systems could lead to unpatched systems, with the user not being aware of.

implementing "not equal" on the other hand doesn't require an order and would at least enable searching for "all packages which aren't the fixed version".

_if_ ordered version numbers are to be implemented, looking at how https://github.com/repology/repology does it may help.

**Comment by ecm75** [comment]
I see the problem... but having a "not equal" operator would also help.
