### ISSUE TITLE
Created objects (owners, machines...) don't show up in the webinterface

### ISSUE THREAD

**Issue by winpat** [idb-project/the-idb#395]
## Environment
* ruby 2.2.4p230
* mysql 5.7.18
* redis-server 2.8.17
* puma webserver
* nginx
```
server {
  listen 80;
  server_name idb.domain.tld;
  location  ~ ^/assets/ {
        root /opt/idb/public/;
  }
  location / {
        proxy_pass http://127.0.0.1:3000;
  }
}
```

## Steps to reproduce
1. Login with LDAP user
2. `+ New Machine`
3. Fill out all fields
4. `Create Machine`

## Expected behavior
The machine shows up in the webinterface.

## Actual behavior
The webinterface is empty. However the host appears in the database:
```
*************************** 3. row ***************************
                                      id: 3
                                    fqdn: testhost.domain.tld
                                      os: NULL
                                    arch: NULL
                                     ram: NULL
                                   cores: NULL
                                  vmhost: NULL
                             serviced_at: NULL
                             description: Some description
                              deleted_at: NULL
                              created_at: 2017-07-12 12:17:12
                              updated_at: 2017-07-12 12:17:12
...
```

## Rails Production Log
```
I, [2017-07-12T14:23:16.433263 #14029]  INFO -- : Started GET "/machines" for 127.0.0.1 at 2017-07-12 14:23:16 +0200
I, [2017-07-12T14:23:16.434179 #14029]  INFO -- : Processing by MachinesController#index as HTML
I, [2017-07-12T14:23:16.444272 #14029]  INFO -- :   Rendering machines/index.html.erb within layouts/application
I, [2017-07-12T14:23:16.448684 #14029]  INFO -- :   Rendered machines/_table.html.erb (2.8ms)
I, [2017-07-12T14:23:16.449327 #14029]  INFO -- :   Rendered machines/index.html.erb within layouts/application (4.5ms)
I, [2017-07-12T14:23:16.452916 #14029]  INFO -- : Completed 200 OK in 19ms (Views: 7.8ms | ActiveRecord: 1.7ms)
```

**Comment by rbns** [comment]
the problem may be due to that the machine has no owner set. usually the first available owner is chosen as default for new items. assuming a fresh installation of the idb: it may be the case that no owner was created before creating the machine, so that no owner could be set for the created machine.

possible fixes for this error would be creating a default owner during installation or preventing creation of items without an owner (showing a appropriate message).

**Comment by winpat** [comment]
@rbns Thanks for your reply. I'm also unable to add owners. Looks like the same problem.

When I try to add a new owner and press save, I get redirectet to `http://idb.domain.tld/owners/${new_owner_id}` and Rails returns an 404.

**Comment by fkr** [comment]
Hi @winpat,

I've tried to reproduce this and so far was not able to do so. I worked with a fresh checkout from develop branch as well as with out latest packages from the 1.6.x release branch.

Your setup was done according to the INSTALL.md?

felix

**Comment by dra** [comment]
no other possible explanation than a missing owner. This cannot happen anymore, as a default owner will be created when needed.
