### ISSUE TITLE
markdown in description field not working properly

### ISSUE THREAD

**Issue by ecm75** [idb-project/the-idb#487]
It seems the markdown codeblock is not working properly, at least in description field:

Starting a codeblock with three back-ticks does not work, it displays the back-ticks and keeps interpreting markdown. Heres an example (replace single quotes with back-ticks, otherwise github will interpret the markdown here...)
```
'''
# This should not be a heading
- This should not be a list
'''
```

**Comment by dra** [comment]
Might you check again, I added some options to the markdown renderer to improve code handling.

**Comment by ecm75** [comment]
Yep, this fixed my markdown problem!

Thank you for the fast fix.
